import { ApiPromise } from '@polkadot/api';
import { SubmittableExtrinsic } from '@polkadot/api/types';
import { DeriveCollectiveProposal } from '@polkadot/api-derive/types';
import { KeyringPair } from '@polkadot/keyring/types';
import { Hash } from '@polkadot/types/interfaces';
export declare function acceptMotion(api: ApiPromise, hash: Hash, index: number): Promise<void>;
export declare function fillTreasury(api: ApiPromise, signer: KeyringPair): Promise<void>;
export declare function proposeMotion(api: ApiPromise, submittableExtrinsic: SubmittableExtrinsic<'promise'>, signer: KeyringPair): Promise<void>;
export declare function getMotion(api: ApiPromise, index: number): Promise<DeriveCollectiveProposal>;
export declare function multiProposeMotion(api: ApiPromise, submittableExtrinsicArray: SubmittableExtrinsic<'promise'>[], signer: KeyringPair): Promise<void>;
export declare function multiGetMotion(api: ApiPromise, indexes: number[]): Promise<DeriveCollectiveProposal[]>;
export declare function multiAcceptMotion(api: ApiPromise, hashes: Hash[], indexes: number[]): Promise<void>;
export declare function extractIndexesFromProposals(bountyProposals: DeriveCollectiveProposal[]): number[];
export declare function extractHashesFromProposals(bountyProposals: DeriveCollectiveProposal[]): Hash[];
